# Generated by Django 3.2.11 on 2022-03-15 09:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('website', models.URLField(blank=True)),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='study_abroad.university')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('MSc', 'MSc'), ('PhD', 'PhD')], max_length=10)),
                ('subject', models.CharField(max_length=250)),
                ('Deadline', models.DateField()),
                ('link', models.URLField(blank=True, null=True)),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='study_abroad.university')),
            ],
        ),
        migrations.CreateModel(
            name='Proffessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('affiliation', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(blank=True, max_length=250)),
                ('website', models.URLField(blank=True, help_text='please use https://')),
                ('researchgate', models.URLField(blank=True, help_text='please use https://')),
                ('Orchid', models.URLField(blank=True, help_text='please use https://')),
                ('google_scholar', models.URLField(blank=True, help_text='please use https://')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proffs', to='study_abroad.program')),
            ],
        ),
    ]
