# Generated by Django 3.2.11 on 2022-03-15 14:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
