# Generated by Django 3.2.11 on 2022-03-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad', '0004_auto_20220322_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='proffessor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profffessors/'),
        ),
        migrations.AddField(
            model_name='university',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='univesity/'),
        ),
    ]
