# Generated by Django 3.2.11 on 2022-03-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad', '0006_program_exted_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='exted_deadline',
            new_name='extended_deadline',
        ),
    ]
