# Generated by Django 3.2.11 on 2022-03-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad', '0007_rename_exted_deadline_program_extended_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='Deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='extended_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
